// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/flights/filter": {
            "post": {
                "description": "Apply filters like price range, airline, or transit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Filter existing flight results",
                "parameters": [
                    {
                        "description": "Filter Criteria",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_flight.FilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/flights/search": {
            "post": {
                "description": "Search flights based on origin, destination, and dates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Search for flights",
                "parameters": [
                    {
                        "description": "Flight Search Criteria",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_flight.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Replace this with your actual Response Struct",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_flight.ArrivalTime": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "internal_flight.DepartureTime": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "internal_flight.FilterOptions": {
            "type": "object",
            "properties": {
                "airlines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "arrival_time": {
                    "$ref": "#/definitions/internal_flight.ArrivalTime"
                },
                "departure_time": {
                    "$ref": "#/definitions/internal_flight.DepartureTime"
                },
                "max_duration": {
                    "type": "integer"
                },
                "max_stops": {
                    "type": "integer"
                },
                "price_range": {
                    "$ref": "#/definitions/internal_flight.PriceRange"
                }
            }
        },
        "internal_flight.FilterRequest": {
            "type": "object",
            "properties": {
                "cabin_class": {
                    "type": "string"
                },
                "departure_date": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "filters": {
                    "$ref": "#/definitions/internal_flight.FilterOptions"
                },
                "origin": {
                    "type": "string"
                },
                "passengers": {
                    "type": "integer"
                },
                "return_date": {
                    "type": "string"
                },
                "sort": {
                    "$ref": "#/definitions/internal_flight.SortOptions"
                }
            }
        },
        "internal_flight.PriceRange": {
            "type": "object",
            "properties": {
                "high": {
                    "type": "integer"
                },
                "low": {
                    "type": "integer"
                }
            }
        },
        "internal_flight.SearchRequest": {
            "type": "object",
            "properties": {
                "cabin_class": {
                    "type": "string"
                },
                "departure_date": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "passengers": {
                    "type": "integer"
                },
                "return_date": {
                    "type": "string"
                }
            }
        },
        "internal_flight.SortOptions": {
            "type": "object",
            "properties": {
                "by": {
                    "description": "price, duration, departure_time, arrival_time, best_value",
                    "type": "string"
                },
                "order": {
                    "description": "asc, desc",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Travel Flight API",
	Description:      "API service for searching and filtering flights.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
